symintr .destroy
symintr .render
symintr .update
symintr .window_hint
symintr .poll_events
symintr .create_window
symintr .make_current
symintr .size
symintr .should_close
symintr .io
symintr .style_colors_dark
symintr .render
symintr .draw_data
symintr .window
symintr .show_demo_window
symintr .text
symintr .button
symintr .init_glfw_opengl
symintr .init_opengl3
symintr .render_draw_data
symintr .glew_init
symintr .viewport
symintr .clear
symintr .clear_color
